### ISSUE TITLE
byte[] value from java reflection is not able to use

### ISSUE THREAD

**Issue by marshall6688** [frida/frida-java#102]
```
    function obj_get(obj, field_name){

        var f = Java.use("java.lang.reflect.Field");
        f = Java.cast(obj.getClass(), clazz).getDeclaredField(field_name);
        f.setAccessible(true);
        var v = f.get(obj)
        if (v == null){
            console.log(v + 'isnull')
        }else{

            console.log(f.getType())
        }
        return v
}
```
var o = obj_get(obj, 'aaa')
console.log(o)

o.getClass() display:
     class [B

appearly    o   is   byte[]
but it is not able to use,       because     o.length  is  undefine

if o.getClass()  is int,   it can be used, 

how to solve the  byte[]  problem,   i spend 2 days,  but i can't  find the way,   thank you 

=============================================

frida  version  12.2.26

**Comment by marshall6688** [comment]
when i did in java:
 ```
   public class HelloWorld {



    public static void main(String[] args) {
        System.out.println("Hello World");

        byte[] a = new byte[10];
        //a.getClass()
        System.out.println(a.getClass().getComponentType().toString());

    }
}

```
Hello World
byte

===========================================================


when i did in Frida js:

     `   console.log('gg----d :: ' + o.getClass().getComponentType());`

i got this:

`[on_message] message: {'type': 'error', 'description': "TypeError: undefined not callable (property 'getComponentType' of [object Object])", 'stack': "TypeError: undefined not callable (property 'getComponentType' of [object Object])\n    at [anon] (duk_js_call.c:2870)\n    at /script1.js:207\n    at input:1", 'fileName': '/script1.js', 'lineNumber': 207, 'columnNumber': 1} data: None`

**Comment by marshall6688** [comment]
but actually is   byte array ,   i  hate  byte  array

**Comment by marshall6688** [comment]
and i check lib/class-factory.js

**Comment by marshall6688** [comment]
just use this,      this.aaa.value

**Comment by zxhubo** [comment]
@marshall6688 I have the same problem，how did you resolved it ？
