### ISSUE TITLE
Frida does not see classes from com.android.server

### ISSUE THREAD

**Issue by diskshared** [frida/frida-java#108]
android 7.0, arm32, frida latest version

This list and another classes not avaliable in frida

* import com.android.server.AppOpsService;
* import com.android.server.AttributeCache;
* import com.android.server.DeviceIdleController;
* import com.android.server.IntentResolver;
* import com.android.server.LocalServices;
* import com.android.server.LockGuard;
* import com.android.server.ServiceThread;
* import com.android.server.SystemService;
* import com.android.server.SystemServiceManager;
* import com.android.server.Watchdog;
* import com.android.server.am.ActivityStack.ActivityState;
* import com.android.server.firewall.IntentFirewall;
* import com.android.server.pm.Installer;
* import com.android.server.statusbar.StatusBarManagerInternal;
* import com.android.server.vr.VrManagerInternal;
* import com.android.server.wm.WindowManagerService;

```javascript
var AppOpsService = Java.use("com.android.server.AppOpsService");
AppOpsService.checkPackage.overload('int', 'java.lang.String').implementation = function(uid,package_name) {
      var result = this.checkPackage(uid,package_name);
      return result; 
  }

```

```
 Error: java.lang.ClassNotFoundException: Didn't find class "com.android.server.AppOpsService" on path: DexPathList[[zip file "/data/app/com.example.ghost-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.ghost-1/lib/arm, /data/app/com.example.ghost-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]  
    at frida/node_modules/frida-java/lib/env.js:227  
    at ensureClass (frida/node_modules/frida-java/lib/class-factory.js:778)  
    at frida/node_modules/frida-java/lib/class-factory.js:164  
    at [anon] (/repl1.js:112)  
    at frida/node_modules/frida-java/lib/vm.js:43  
    at frida/node_modules/frida-java/index.js:280  
    at /repl1.js:158
```
This class is in the system. When I run my application (com.example.ghost), I see an error in the log

```javascript
02-08 21:38:26.588  5667  6809 W AppOps  : Bad call: specified package com.example.ghost under uid 10120 but it is really 10113
02-08 21:38:26.588  5667  6809 W AppOps  : java.lang.RuntimeException: here
02-08 21:38:26.588  5667  6809 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java)
02-08 21:38:26.588  5667  6809 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java)
02-08 21:38:26.588  5667  6809 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java)
02-08 21:38:26.588  5667  6809 W AppOps  :      at android.os.Binder.execTransact(Binder.java)
```

Through the Frida I want to intercept method AppOpsService.checkPackageand disable the error

**Comment by diskshared** [comment]
i solved this problem

**Comment by plus1998** [comment]
> i solved this problem

how, pls...
