### ISSUE TITLE
Crashes on second session with Java

### ISSUE THREAD

**Issue by hedger** [frida/frida-java#11]
I compiled a sample agent coming with frida-java (`/test/agent/index.js`), and it crashes target application on second run.
I build it with `frida-compile index -o myjava.js` and start it up with `frida -U -l myjava.js com.android.terminal`
and execute the following code in REPL:
```
rpc.exports.hookJavaMethod();
for (var i = 0; i < 4; ++i) { rpc.exports.callJavaMethod(); }
console.log(rpc.exports.getHookTriggerCount())
```
First run always completes without errors, but on the second one it always crashes target application, printing stack traces like
```
Error: Can't access the string.
    at repl1.js:3416
    at repl1.js:2758
    at getHost (input:1)
    at apply (native)
    at f (repl1.js:1461)
    at repl1.js:5609
    at call (native)
    at getHost (input:1)
```
or 
```
Error: java.lang.StackOverflowError: stack size 1013KB
    at repl1.js:2759
    at getHost (input:1)
    at apply (native)
    at f (repl1.js:1461)
    at repl1.js:5609
    at call (native)
    at getHost (input:1)
Process terminated
```

**Comment by oleavr** [comment]
Thanks! I think this is the exact issue reproduced every single time by our new test-suite. Could you try `make check` on your device and check how that goes?
