### ISSUE TITLE
Can't Find OkHttp3 (bypass)

### ISSUE THREAD

**Issue by hadi500** [frida/frida-java#116]
```
My Frida Script:

```
setTimeout(function() {
    Java.perform(function() {
        try {
            var CertificatePinner = Java.use('okhttp3.CertificatePinner');
            console.log("[+] OkHTTP 3.x Found");
            CertificatePinner.check.overload('java.lang.String', 'java.util.List').implementation = function() {
                console.log("[+] OkHTTP 3.x check() called. Not throwing an exception.");
            };
        } catch (err) {
            console.log("[-] OkHTTP 3.x Not Found")
        }
}, 0);
```

i need to bypass the ssl pinning but frida can't find "okhttp3.CertificatePinner",
Where is my job wrong?

**Comment by thejunkjon** [comment]
You might want to double check that you are running your script against a debug version of your application and that minifcation (obfuscation) is disabled.  You can also run the command "dexdump <apk_path> | grep okhttp3" and see if "CertificatePinner" is listed in the output.
