### ISSUE TITLE
Support for enumerating loaded classes on ART

### ISSUE THREAD

**Issue by oleavr** [frida/frida-java#17]
Continuation of frida/frida-core#75. As described by @dpnishant:

Running the following on Android 5.1.1 on Nexus 5

`var classes = Java.enumerateLoadedClassesSync();`

throws the following error.

```
Error: Enumerating loaded classes is only supported on Dalvik for now
    at _enumerateLoadedClasses (gumjs-java.js:172:23)
```

**Comment by oleavr** [comment]
Implemented in 5977cebdcabecdd9e3594d2941d0ad15c6aa18dd.

**Comment by dpnishant** [comment]
Awesome! 👍

**Comment by TheCjw** [comment]
Cooool.
