### ISSUE TITLE
Error enumerating loaded classes (9.1.14)

### ISSUE THREAD

**Issue by SrFlipFlop** [frida/frida-java#23]
Hi,

I'm trying to enumerate loaded classes using Android 5.0.1 emulator with the following script:   
`
if (Java.available) { 
    Java.enumerateLoadedClasses({
        onMatch: function(className) {
            send(className);
        }
    });
} else {
    send("Not available Java");
}
` 

Using Frida 9.1.7 it give me the following error:
`{u'columnNumber': 1, u'description': u'Error: Enumerating loaded classes is only supported on Dalvik for now', u'fileName': u'frida/node_modules/frida-java/index.js', u'lineNumber': 87, u'type': u'error', u'stack': u'Error: Enumerating loaded classes is only supported on Dalvik for now\n    at c (frida/node_modules/frida-java/index.js:87)\n    at frida/node_modules/frida-java/index.js:143\n    at script1.js:7'}`

Seeing that the above error had already been notified, I try a newer Frida versions (9.1.14 and 9.1.13) and it give me a different error:
`{u'columnNumber': 1, u'description': u'Error: VM::GetEnv failed: -2', u'fileName': u'frida/node_modules/frida-java/lib/result.js', u'lineNumber': 7, u'type': u'error', u'stack': u'Error: VM::GetEnv failed: -2\n    at e (frida/node_modules/frida-java/lib/result.js:7)\n    at frida/node_modules/frida-java/lib/vm.js:53\n    at h (frida/node_modules/frida-java/index.js:166)\n    at frida/node_modules/frida-java/index.js:105\n    at script1.js:7'}`

To discard that the error was provoked by the Android version, I also tried to use Android 6.0 but the same error message was disclosed.emulator and have the same error.

I hope that all the information help you to find the error more quickly. Thanks for the great open source project that is Frida.

Ferran Obiols.

**Comment by oleavr** [comment]
Thanks for reporting. The issue here is that it is forbidden to call any `Java` APIs outside of `Java.perform()`. Please ensure your `Java.enumerateLoadedClasses()` call happens inside a `Java.perform()`. Cheers!

**Comment by SrFlipFlop** [comment]
Thanks, with this correction my script works correctly.
