### ISSUE TITLE
Error: access violation accessing 0x6f0056

### ISSUE THREAD

**Issue by Fi5t** [frida/frida-java#28]
I've faced with a strange problem. When I try to spawn android app via Frida then I get an error.

`frida -U --no-pause -f com.android.chrome -l script.js`

```
Spawned `com.android.chrome`. Resuming main thread!
[USB::LGE Nexus 5::['com.android.chrome']]-> Error: access violation accessing 0x6f0056
    at frida/node_modules/frida-java/lib/env.js:206
    at apply (native)
    at frida/node_modules/frida-java/lib/env.js:201
    at frida/node_modules/frida-java/lib/class-factory.js:113
    at frida/node_modules/frida-java/lib/class-factory.js:1621
    at call (native)
    at getPackageInfoNoCheck (input:1)
    at apply (native)
    at r (frida/node_modules/frida-java/lib/class-factory.js:842)
    [...]
```
My **script.js** looks like this
```
Java.perform(function () {
    var Activity = Java.use("android.app.Activity");
    Activity.onResume.implementation = function () {
        console.log("[*] onResume() got called!");
        this.onResume();
    };
});
```

**Frida version**: 9.1.25
**Android version**: 6.0.1

**Comment by TheDauntless** [comment]
I have the same issue, though with different memory address on:

**Frida version:** 9.1.25
**Android version:** 7.1.1

If you change `Java.perform` to `Java.performNow`, it seems to work though. I couldn't find documentation about the difference, so I don't know what any other impact may be.

**Comment by TheDauntless** [comment]
This appears to be the same issue as #27.

Java.perform tries to wait for getPackageInfoNoCheck to be called in order to execute the given function. Apparently though, the (Android part of the) Java VM isn't fully instantiated yet, giving this error. Using performNow works because it doesn't have the getPackageInfoNoCheck trick. The caveat is that you won't be able to use any Android classes yet, only Java classes.

**Comment by mohe2015** [comment]
@TheDauntless but for me it worked to hook android.app.Activity.onResume using performNow. Is that not an Android class?

**Comment by TheDauntless** [comment]
(This is all based on research and chats on Telegram, but...) You shouldn't be able to access the internal app classes yet. If you can indeed already access android.app.Activity, I still don't know why it crashes :/

**Comment by mohe2015** [comment]
If I do that it does not crash any more and the log tells you onResume got called so it is definitely working.

**Comment by alvarofe** [comment]
I'm having the same issue but there are many issues opened already related with this imho. This could be organized into a single issue to make @oleavr et al life easier

**Comment by enovella** [comment]
Tickets #25 #26 #28 #29  are indeed the same issue and could be merged into one.

**Comment by oleavr** [comment]
Same as #29, let's keep tracking it there since it has more details.
