### ISSUE TITLE
Emulator crashes on x86_64

### ISSUE THREAD

**Issue by TheDauntless** [frida/frida-java#33]
**Version:** Frida-server 10.1.6

When launching the application through frida, the emulator crashes. This may be related to the modification to fix #29 

`frida -U -f com.mwr.dz `

<pre>07-11` 15:04:09.443 25859 26502 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.mwr.dz cmp=com.mwr.dz/.activities.MainActivity} from uid 10021 on display 0
--------- beginning of crash
07-11 15:04:09.453 25761 25761 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x2008 in tid 25761 (main)
07-11 15:04:09.454 21698 21698 W         : debuggerd: handling request: pid=25761 uid=0 gid=0 tid=25761
07-11 15:04:09.460 27365 27365 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-11 15:04:09.460 27365 27365 F DEBUG   : Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:7.1.1/NYC/3756122:userdebug/test-keys'
07-11 15:04:09.460 27365 27365 F DEBUG   : Revision: '0'
07-11 15:04:09.460 27365 27365 F DEBUG   : ABI: 'x86'
07-11 15:04:09.461 27365 27365 F DEBUG   : pid: 25761, tid: 25761, name: main  >>> zygote <<<
07-11 15:04:09.461 27365 27365 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2008
07-11 15:04:09.461 27365 27365 F DEBUG   :     eax 00000001  ebx e8fa9958  ecx e50834b4  edx e508305c
07-11 15:04:09.461 27365 27365 F DEBUG   :     esi db91f960  edi db8d7b80
07-11 15:04:09.461 27365 27365 F DEBUG   :     xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000006b  xss 0000002b
07-11 15:04:09.461 27365 27365 F DEBUG   :     eip e8f96516  ebp 00002000  esp ffd846e0  flags 00000246
07-11 15:04:09.461 27365 27365 F DEBUG   : 
07-11 15:04:09.461 27365 27365 F DEBUG   : backtrace:
07-11 15:04:09.461 27365 27365 F DEBUG   :     #00 pc 00027516  /system/lib/libjavacore.so
07-11 15:04:09.510  1330  1378 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x933 imply creation of host color buffer
07-11 15:04:09.513 25859 25905 D         : HostConnection::get() New Host Connection established 0x7adb5d946d00, tid 25905
07-11 15:04:09.580 25859 26096 W NativeCrashListener: Couldn't find ProcessRecord for pid 25761
07-11 15:04:09.584 25859 25900 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
07-11 15:04:09.585 21698 21698 W         : debuggerd: resuming target 25761
07-11 15:04:09.641 25859 27196 E Process : Starting VM process through Zygote failed
07-11 15:04:09.642 25859 27196 E ActivityManager: Failure starting process com.mwr.dz
07-11 15:04:09.642 25859 27196 E ActivityManager: java.lang.RuntimeException: Starting VM process through Zygote failed
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.os.Process.start(Process.java:527)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3798)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3655)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3536)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1419)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2577)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2127)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1829)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityStack.completePauseLocked(ActivityStack.java:1332)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityStack.activityPausedLocked(ActivityStack.java:1212)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityManagerService.activityPaused(ActivityManagerService.java:6919)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:571)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2795)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
07-11 15:04:09.642 25859 27196 E ActivityManager: Caused by: android.os.ZygoteStartFailedEx: java.io.IOException: Connection reset by peer
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.os.Process.zygoteSendArgsAndGetResult(Process.java:618)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.os.Process.startViaZygote(Process.java:737)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.os.Process.start(Process.java:521)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	... 13 more
07-11 15:04:09.642 25859 27196 E ActivityManager: Caused by: java.io.IOException: Connection reset by peer
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.net.LocalSocketImpl.readba_native(Native Method)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.net.LocalSocketImpl.-wrap1(LocalSocketImpl.java)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.net.LocalSocketImpl$SocketInputStream.read(LocalSocketImpl.java:110)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at java.io.DataInputStream.readFully(DataInputStream.java:198)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at java.io.DataInputStream.readInt(DataInputStream.java:389)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	at android.os.Process.zygoteSendArgsAndGetResult(Process.java:609)
07-11 15:04:09.642 25859 27196 E ActivityManager: 	... 15 more
07-11 15:04:09.642 25859 27196 I ActivityManager: Force stopping com.mwr.dz appid=10072 user=0: start failure
07-11 15:04:09.642 25859 27196 I ActivityManager:   Force finishing activity ActivityRecord{16bc084 u0 com.mwr.dz/.activities.MainActivity t31}
07-11 15:04:09.645 25859 27196 W ActivityManager: Slow operation: 192ms so far, now at startProcess: done starting proc!
07-11 15:04:09.645 25859 25882 I ActivityManager: Exiting empty application process 0:com.mwr.dz/u0a72 (null)
07-11 15:04:09.645 25859 25882 D ActivityManager: cleanUpApplicationRecord -- 0</pre>

**Comment by oleavr** [comment]
Fixed in latest versions of Frida.
