### ISSUE TITLE
"stack": TypeError: undefined not callable on calling the original method inside new implementation

### ISSUE THREAD

**Issue by tarunmangla** [frida/frida-java#35]
I am trying to modify one of the function in a closed apk (no access to source code). After doing my own stuff I call the original method. However, I get an error message _"stack": TypeError: undefined not callable_ 

I am using the following script (taken from the tutorial)
	`	Java.perform(function () {
	var handle = Java.use("com.hulu.physicalplayer.PhysicalPlayer");
	handle.pause.implementation = function () {
                                //console.log("pause called")
				this.pause()
	}
	})`

Interestingly, I am able to call other methods (example this.play()) of the same class while inside the new implementation of pause function. However call to pause function gives me the above error.

I tried modifying some other functions as well, but similar thing happens i.e. I get an error message when calling the original function inside the new method.

Here is the full error:
_{u'columnNumber': 1, u'description': u'TypeError: undefined not callable', u'fileName': u'java.js', u'lineNumber': 2513, u'type': u'error', u'stack': u'TypeError: undefined not callable\n    at [anon] (duk_js_call.c:842)\n    at v (frida/node_modules/frida-java/lib/android.js:575)\n    at resolveArtTargetMethodId (frida/node_modules/frida-java/lib/class-factory.js:1200)\n    at pause (input:1)\n    at apply (native)\n    at r (frida/node_modules/frida-java/lib/class-factory.js:940)\n    at script1.js:6\n    at call (native)\n    at pause (input:1)'}_

**Comment by oleavr** [comment]
Please open a new issue if this is still reproducible.
