### ISSUE TITLE
How to get all java class fields/methods in frida?

### ISSUE THREAD

**Issue by douniwan5788** [frida/frida-java#44]
After dig into source, I finally found the way to get a field which has the same name of a method.

https://github.com/frida/frida-java/blob/82bc59a8389ae62a94e65841b34bb003e03f6518/lib/class-factory.js#L810-L813
```java
public class Test {
    private static int a = 1;
    
    private static int a()
    {
        return 0;
    }
}
```

```js
'use strict';

if (Java.available) {
    console.log('Java Process!')

    Java.perform(function () {
        var Test = Java.use("Test");

        console.log( Test._a.value );

    });
} else
    console.log("not Java Process!")
````

My question is: 
Is there a way to get all fields/methods of a java class?

**Comment by douniwan5788** [comment]
find a way
```js
console.log( Object.getOwnPropertyNames(Test.__proto__).join('\n') );
```

**Comment by wb14123** [comment]
I've spent a lot of time to figure out how to get the fields which have the same name of methods. Can we put this in the document?

**Comment by wb14123** [comment]
BTW, @douniwan5788 are you figuring it out by reading the source code?

**Comment by iddoeldor** [comment]
> find a way
> 
> ```js
> console.log( Object.getOwnPropertyNames(Test.__proto__).join('\n') );
> ```
Get Java class methods & members
```js
function describeJavaClass(className) {
  var jClass = Java.use(className);
  console.log(JSON.stringify({
    _name: className,
    _methods: Object.getOwnPropertyNames(jClass.__proto__).filter(function(m) {·
      return !m.startsWith('$') // filter out Frida related special properties
        || m == 'class' || m == 'constructor' // optional
    }), 
    _fields: jClass.class.getFields().map(function(f) {
      return f.toString()
    })  
  }, null, 2));
}
```

**Comment by 0x410c** [comment]
empty method list
obtain like the fields :

`db1.class.getMethods()`

**Comment by KANGOD** [comment]
@wb14123 
> I've spent a lot of time to figure out how to get the fields which have the same name of methods. Can we put this in the document?

Indeed there is one, `this._m.value` in https://github.com/frida/frida-website/blob/master/_docs/examples/android.md. While it's in [Examples](https://frida.re/docs/examples/android/) section instead of [API Reference](https://frida.re/docs/javascript-api/), I can't say it's well documented. 
frida/frida#833 is also the same topic. Maybe a doc PR is needed.

**Comment by wb14123** [comment]
@KANGOD Yes I added that one to the doc :smile:

**Comment by mmkhitaryan** [comment]
I think @0x410c meant to use "of" instead of "in".
```
for(var m of methodArr)
```
```var m in```returns a list of indices instead of objects. Calling ```0.class.getMethods()``` returns error: TypeError: cannot read property 'getMethods' of undefined
