### ISSUE TITLE
java.lang.ClassNotFoundException when using Java.registerClass

### ISSUE THREAD

**Issue by ali-alidoust** [frida/frida-java#49]
I get the following error when I use Java.registerClass:
The device is an ARMv7 running Android 4.4.4
```
Error: java.lang.ClassNotFoundException: Didn't find class "com.example.MyRunnable" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/lib]]', u'fileName': u'frida/node_modules/frida-java/lib/env.js', u'lineNumber': 218, u'type': u'error', u'stack': u'Error: java.lang.ClassNotFoundException: Didn't find class "com.example.MyRunnable" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    at frida/node_modules/frida-java/lib/env.js:218
    at ensureClass (frida/node_modules/frida-java/lib/class-factory.js:435)
    at frida/node_modules/frida-java/lib/class-factory.js:119
    at registerClass (frida/node_modules/frida-java/lib/class-factory.js:1637)
    at script1.js:11
    at frida/node_modules/frida-java/lib/vm.js:39
    at frida/node_modules/frida-java/index.js:281
    at script1.js:15'}
```

Here is the code that produces the error:
```javascript
Java.perform(function() {
    var Runnable = Java.use('java.lang.Runnable');
    var MyRunnable = Java.registerClass({
        name: 'com.example.MyRunnable',
        implements: [Runnable],
        methods: {
            'run': function() {
                console.log('Hello!!!');
            }
        }
    });

    var runnable = MyRunnable.$new();
    runnable.run();
});
```

**Comment by yehgdotnet** [comment]
same issue here.

**Comment by oleavr** [comment]
`Java.registerClass()` is only supported on ART for now. Supporting this on Dalvik is not a priority for me personally, but PRs welcome!

**Comment by yehgdotnet** [comment]
Got clear answer that why objection that relies on Frida didn't work in Android 4.4 when I ran ssl pinning disable.    Reverted to Xposed framework.

**Comment by yehgdotnet** [comment]
Thank you, oleavr

**Comment by WooyunDota** [comment]
I got same error on android 6.0 which is ART....
But,leavr's example "javax.net.ssl.X509TrustManager"  this interface has not the problem.

**Comment by yehgdotnet** [comment]
I don't understand what you mean @WooyunDota 
I tested only on Android 7.     You mean this doesn't work in Android 6.

**Comment by WooyunDota** [comment]
@yehgdotnet Thank for you response.
I mean when I use "javax.net.ssl.X509TrustManager" to registerClass will success.
But,I use other interface like "java.lang.Runnable" or "javax.net.ssl.HostnameVerifier" to registerClass will fail.
The error message is Error: java.lang.ClassNotFoundException: Didn't find class ....

**Comment by yehgdotnet** [comment]
Insteresting. Maybe you root Emulator of Android 7 and try again if you dont have Android 7+ device.

**Comment by WooyunDota** [comment]
@yehgdotnet can't work too.
Attaching...                                                            
registerClass from Runnable >>>>>>>> java.lang.ClassNotFoundException: Didn't find class "com.example.MyRunnable" on path: DexPathList[[zip file "/data/data/com.example.mennomorsink.webviewtest2/cache/raw306036453dex"],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
[Genymotion Google Nexus 5X - 7.0.0 - API 24 - 1080x1920::com.example.mennomorsink.webviewtest2]->

**Comment by yehgdotnet** [comment]
Can you post your sample class here. I will try with my devices.

**Comment by WooyunDota** [comment]
@yehgdotnet 
`Java.perform(function() {
    try {
        var Runnable = Java.use('java.lang.Runnable');
        var MyRunnable = Java.registerClass({
            name: 'com.example.MyRunnable',
            implements: [Runnable],
            methods: {
                'run': function() {
                    console.log('Hello!!!');
                }
            }
        });
        var runnable = MyRunnable.$new();
        runnable.run();
    } catch (e) {
        //registerClass from Runnable >>>>>>>> java.lang.ClassNotFoundException: Didn't find class "com.example.MyRunnable" on path: DexPathList[[zip file "/data/data/com.example.mennomorsink.webviewtest2/cache/raw1742406138dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        console.log("registerClass from Runnable >>>>>>>> " + e.message);
    }
});
`
