### ISSUE TITLE
SIGABRT on android 4.4 x86

### ISSUE THREAD

**Issue by va1d3z** [frida/frida-java#52]
vm aborting because of wrong jniarginfo value (0x80000000)
frida must realize [computeJniArgInfo](http://androidxref.com/4.4.4_r1/xref/dalvik/vm/oo/Class.cpp#2283) to calculate jniarginfo

**Comment by oleavr** [comment]
PRs welcome. Otherwise, Dalvik is not a priority for me personally as I'm only using Frida on ART these days.
