### ISSUE TITLE
Intercept OutputStream functions

### ISSUE THREAD

**Issue by hahanov** [frida/frida-java#58]
I can not intercept OutputStream functions, what is the problem?
write.overload('int') - does not intercept
write.overload('[B','int','int') - does not intercept 
write.overload('[B') - intercepts, working
```
jscode = """
setImmediate(function() {
    console.log("[*] Starting script");
    Java.perform(function() {
      bClass = Java.use("java.io.OutputStream");
	  bClass.write.overload('int').implementation = function(x) { 
         console.log("[*] rS print data int "+x);
      }
	  bClass.write.overload('[B').implementation = function(x) { 
         console.log("[*] rS print data int "+x); //Working
      }
	     bClass.write.overload('[B','int','int').implementation = function(b,y,z) { 
         console.log("[*] rS print data otvet "+b);
      }
      console.log("[*]  Running sniffer")

    })
})
"""
```
java.io.OutputStream source - https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/io/OutputStream.java
Android 7.1.1 
Frida 10.5.15
Thank you in advance.

**Comment by oleavr** [comment]
You cannot assume that the base class methods will be called – keep in mind that subclasses exist and may be overriding any of them.
