### ISSUE TITLE
Get method and class name the are called through reflection in android

### ISSUE THREAD

**Issue by waqarrashid33** [frida/frida-java#60]
Hello everyone,

I am trying to get the class name and method name that are called using reflection in android.
I get the parameters that are passed to the invoke method but those are kind of addresses (sorry new to Frida and android development) and I don't know how to get the corresponding class and method names from it. Here is sample output from one of the reflection call:

`{"class":"java.lang.reflect.Method","method":"invoke","args":[{"$handle":"0x10098a","$weakRef":387},[{"$handle":"0x10098e","$weakRef":388}]],"retVal":null}`

Above I log the class and method that are hooked along with the parameters to them. Now I need to get Class and method name that were called using the invoke method. Any pointers in the right direction would be highly appreciated.

Cheers.
Waqar

**Comment by waqarrashid33** [comment]
Something similar: https://github.com/frida/frida/issues/310

**Comment by waqarrashid33** [comment]
I solved this thingy by combing through the code of Frida-Java..
Java.cast method seems similar but it needs the name of class and returns instance of that object. What we need is just name of the class from the handle. By having a look at the source of Java.cast, I found a line which was doing exactly the same that is getting the name of class given a handle to its instance.

https://github.com/frida/frida-java/blob/b564b52d1052081dd7ee9abb6a854080d8e63745/lib/class-factory.js#L703

So my solution was:

`Java.vm.getEnv().getObjectClassName(obj.$handle)`

which returns the name of the class.

**Comment by oleavr** [comment]
@waqarrashid33 You can also use `obj.$className` to get the class-name of an object.

**Comment by waqarrashid33** [comment]
Thanks. I figured it out later. Currently I am working on parameters, sometimes they are buffers and I still hadn't figured out how to get their contents.
Also do you know of way to get Class names of static methods, there is one getDeclaredAnnotations but I that returns the class in which it was made. I want the name of class from which it was called. Not sure if it makes sense.

**Comment by waqarrashid33** [comment]
For method name that was called using the reflection, we can use this.getName() inside the implementation of "invoke".

**Comment by waqarrashid33** [comment]
this.toString() prints useful info about the method like return type, parameters etc.
Have a look at Method Class in Android documentation to see all the cool stuff that can be done with it.
