### ISSUE TITLE
Hook class initializer

### ISSUE THREAD

**Issue by awakened1712** [frida/frida-java#62]
Is there a way to hook a class initializer? For example:

```java
class MainActivity {
    static {  // <=== clinit method that I want to hook
        System.loadLibrary("test");
    }
}
```

**Comment by enovella** [comment]
What about `MainActivity.$new()`?  I'm afraid that you cannot hook it due to the early instrumentation issue (https://github.com/frida/frida-java/issues/29).

**Comment by oleavr** [comment]
I didn't look into this, but I would encourage you to dig into it. Once you find out, please open a PR against frida-website documenting how to do it.

**Comment by daMatz** [comment]
Is there documentation how to do this?

**Comment by mnalmahmud** [comment]
@oleavr 
> I didn't look into this, but I would encourage you to dig into it. Once you find out, please open a PR against frida-website documenting how to do it.

Is this still open? I may have some solutions for this. Atleast for android. If its necessary for both JVM and Android features to be 1:1 then i might would look into JVM's stuff as well.
