### ISSUE TITLE
Hook System.loadLibrary

### ISSUE THREAD

**Issue by awakened1712** [frida/frida-java#63]
I have the below code to hook System.loadLibrary()
```javascript
var System = Java.use.('java.lang.System');
System.loadLibrary.implementation = function(name) {
    console.log("System.loadLibrary " + name); // it is ok until this point
    this.loadLibrary(name);
    console.log("loadLibrary"); // <== this does not get printed out
    // code to hook 
};
```
I want to hook some C native function after the library is loaded. So I must have some code after the original loadLibrary is called. However, as can be seen from my snippet, codes starting from `console.log("loadLibrary"); ` does not get executed.

Did I do anything wrong?

**Comment by enovella** [comment]
Can you post the entire hook? Are you using `Java.use()`?

Why dont you try to hook `dlopen()` through `Interceptor`? Please look at the Frida JS API for that.

Cheers

**Comment by awakened1712** [comment]
@enovella :+1: thanks man, that's a good idea. I've just tried and that worked. But still it's weird that I cannot hook `System.loadLibrary()`. Is there any reason behind?

**Comment by enovella** [comment]
Several things:

- `Java.use` requires capital `J`
- Is the System.load() call within the main activity? Perhaps it's an issue regarding early instrumentation.
- Why dont you try these hooks hosted at Frida CodeShare? https://codeshare.frida.re/@dzonerzy/whereisnative/

Cheers

**Comment by enovella** [comment]
> Is the System.load() call within the main activity? Perhaps it's an issue regarding early instrumentation.

Something to add in here?

**Comment by awakened1712** [comment]
No, there was no System.load()

**Comment by awakened1712** [comment]
I suspect that it could be something similar to this https://github.com/rovo89/XposedBridge/issues/87

Though, Runtime.loadLibrary() does not take any effect either.

**Comment by awakened1712** [comment]
this guy reported the same problem also https://github.com/frida/frida-gum/issues/255

**Comment by enovella** [comment]
> this guy reported the same problem also frida/frida-gum#255

The call is in the `MainActivity` as I asked you.

**Comment by awakened1712** [comment]
@enovella as said "No, there was no System.load()"

```java
public class MainActivity extends Activity {
    static {
        System.loadLibrary("foo");
    }
    // ...
```

**Comment by oleavr** [comment]
Same issue as rovo89/XposedBridge#87 -- and the reason it doesn't reach the next line is because it throws a Java exception.

**Comment by jeanbmar** [comment]
You can actually hook System.loadLibrary doing this:
```
Java.perform(function() {
    const SystemDef = Java.use('java.lang.System');
    const RuntimeDef = Java.use('java.lang.Runtime');
    const SystemLoad_2 = SystemDef.loadLibrary.overload('java.lang.String');
    const VMStackDef = Java.use('dalvik.system.VMStack');

    SystemLoad_2.implementation = function(library) {
        send("Loading dynamic library => " + library);
        try {
            let loaded = RuntimeDef.getRuntime().loadLibrary0(VMStackDef.getCallingClassLoader(), library);
            if(library === 'myLib') {
                //do my stuff
            }
            return loaded;
        } catch(ex) {
            console.log(ex);
        }
    };
});
```

**Comment by awakened1712** [comment]
@jeanbmar thanks dude, this is awesome.

**Comment by srcdes** [comment]
```
Error: java.lang.UnsatisfiedLinkError: Library mylib not found; tried [/vendor/lib/libmylib.so, /system/lib/libmylib.so]
```

**Comment by srcdes** [comment]
@jeanbmar It doesn't work on Android 5. Anyway, how can i intercept methods of the library catched in 'if(library === 'myLib') { ... }' block?

**Comment by jeanbmar** [comment]
> @jeanbmar How can i intercept methods in the library catched using `if(library === 'myLib') { ... }` block? I have only library name string `library`.

The block is just telling you the library has been loaded.
From there you can use the regular Frida API, such as Process.findModuleByName, to do your stuff.

**Comment by buchisu** [comment]
> > @jeanbmar How can i intercept methods in the library catched using `if(library === 'myLib') { ... }` block? I have only library name string `library`.
> 
> The block is just telling you the library has been loaded. From there you can use the regular Frida API, such as Process.findModuleByName, to do your stuff.

I use 'var model = Process.findModuleByName("xxxx.so");' in the block but the model is null, why?

**Comment by BLuFeNiX** [comment]
> You can actually hook System.loadLibrary doing this (Android 7.1):
> 
> ```
> Java.perform(function() {
>     const System = Java.use('java.lang.System');
>     const Runtime = Java.use('java.lang.Runtime');
>     const SystemLoad_2 = System.loadLibrary.overload('java.lang.String');
>     const VMStack = Java.use('dalvik.system.VMStack');
> 
>     SystemLoad_2.implementation = function(library) {
>         send("Loading dynamic library => " + library);
>         try {
>             const loaded = Runtime.getRuntime().loadLibrary0(VMStack.getCallingClassLoader(), library);
>             if(library === 'myLib') {
>                 //do my stuff
>             }
>             return loaded;
>         } catch(ex) {
>             console.log(ex);
>         }
>     };
> });
> ```

`loadLibrary0` is a `void` method, so capturing the return value and returning it has no effect. This confused me for a while, as I was attempting to us that return value to detect if the library had been successfully loaded. This also means you can't return a null ptr or swap the library after a call to `loadLibrary0` has been made.

**Comment by jeanbmar** [comment]
> > You can actually hook System.loadLibrary doing this (Android 7.1):
> > ```
> > Java.perform(function() {
> >     const System = Java.use('java.lang.System');
> >     const Runtime = Java.use('java.lang.Runtime');
> >     const SystemLoad_2 = System.loadLibrary.overload('java.lang.String');
> >     const VMStack = Java.use('dalvik.system.VMStack');
> > 
> >     SystemLoad_2.implementation = function(library) {
> >         send("Loading dynamic library => " + library);
> >         try {
> >             const loaded = Runtime.getRuntime().loadLibrary0(VMStack.getCallingClassLoader(), library);
> >             if(library === 'myLib') {
> >                 //do my stuff
> >             }
> >             return loaded;
> >         } catch(ex) {
> >             console.log(ex);
> >         }
> >     };
> > });
> > ```
> 
> `loadLibrary0` is a `void` method, so capturing the return value and returning it has no effect. This confused me for a while, as I was attempting to us that return value to detect if the library had been successfully loaded. This also means you can't return a null ptr or swap the library after a call to `loadLibrary0` has been made.

Yeah this was for Android 7, things might have changed since!

**Comment by BLuFeNiX** [comment]
> Yeah this was for Android 7, things might have changed since!

@jeanbmar No, Android 7 also used `void`: http://androidxref.com/7.0.0_r1/xref/libcore/ojluni/src/main/java/java/lang/Runtime.java#959

And that method didn't exist in Android 6, so it's always been void :)

**Comment by quickbird8888** [comment]
The following code is adapted for newer versions of Android

const System = Java.use('java.lang.System');
const Runtime = Java.use('java.lang.Runtime');
const VMStack = Java.use('dalvik.system.VMStack');
//load:
System.load.implementation = function(library) {
	console.log("load called start with: " + library);
	Runtime.getRuntime().load0(VMStack.getStackClass1(), library);
	console.log("load called end with: " + library);
};

//loadLibrary:
System.loadLibrary.implementation = function(library) {
	console.log("loadLibrary called start with: " + library);
	Runtime.getRuntime().load0(VMStack.getCallingClassLoader()(), library);
	console.log("loadLibrary called end with: " + library);
};

//use android_dlopen_ext before calling JNI_OnLoad
var dlopenPtr = Module.findExportByName(null, "android_dlopen_ext");
Interceptor.attach(dlopenPtr, {
    onEnter: function (args) {
        this.libPath = args[0].readUtf8String();
        console.log("android_dlopen_ext called start with: " + this.libPath);
    },
    onLeave: function (retval) {
		console.log("android_dlopen_ext called end with: " + this.libPath);
	}
});

**Comment by quickbird8888** [comment]
The following code is adapted for newer versions of Android

const System = Java.use('java.lang.System');
const Runtime = Java.use('java.lang.Runtime');
const VMStack = Java.use('dalvik.system.VMStack');
//load:
System.load.implementation = function(library) {
        console.log("load called start with: " + library);
	Runtime.getRuntime().load0(VMStack.getStackClass1(), library);
	console.log("load called end with: " + library);
};
//loadLibrary:
System.loadLibrary.implementation = function(library) {
	console.log("loadLibrary called start with: " + library);
	Runtime.getRuntime().load0(VMStack.getCallingClassLoader()(), library);
	console.log("loadLibrary called end with: " + library);
};

//use android_dlopen_ext before calling JNI_OnLoad
var dlopenPtr = Module.findExportByName(null, "android_dlopen_ext");
Interceptor.attach(dlopenPtr, {
    onEnter: function (args) {
        this.libPath = args[0].readUtf8String();
        console.log("android_dlopen_ext called start with: " + this.libPath);
    },
    onLeave: function (retval) {
		console.log("android_dlopen_ext called end with: " + this.libPath);
	}
});
