### ISSUE TITLE
How to hook dynamic load dex class?

### ISSUE THREAD

**Issue by bluzye** [frida/frida-java#65]
// dynamic_loader is a ClassLoader instance
var cls = dynamic_loader.findClass("xxx.xxx.xxx");

cls.a.implementation = ...   // Fail !!!

Is there any way to handle this？
How to convert cls to JS klass wrapper?

Sorry, my English is not good.

**Comment by enovella** [comment]
Very hard to understand you, sorry. Could you maybe provide better code snippets? If your English isn't so good, try to use as much code as possible to guide us to spot the error.

**Comment by bluzye** [comment]
com.xxx.xxx.apk dynamic load dyn.dex
I use scirpt inject to com.xxx.xxx.apk, but i expect to hook class(dyn.classA) is in dyn.dex.

var bm= Java.use("com.xxx.xxx.bm");
    bm.$init.implementation = function (ctx, conf) {
    	this.$init(ctx, conf);

    	var mi_obj = mi.$new();
        // This loader is DexClassLoader for dyn.dex
    	var loader = mi.e.overload("com.xxx.xxx.md").call(mi_obj, conf);
    	bmi.$dispose(mi_obj);

       // Use Java method get Class<?>
    	var cls = loader.findClass("dyn.classA");
    	
      // is there any way to hook method of dyn.classA ?
      // can't use Java.use("dyn.classA"),   error: class not found
      // cls.a.implementation = ..., error: a is undefined
     // How to convert cls to klass return by Java.use()? 
    }

**Comment by bluzye** [comment]
I got it!

**Comment by pharazone** [comment]
same problem, how to solve this, please

**Comment by xingkong123600** [comment]
> com.xxx.xxx.apk dynamic load dyn.dex
> I use scirpt inject to com.xxx.xxx.apk, but i expect to hook class(dyn.classA) is in dyn.dex.
> 
> var bm= Java.use("com.xxx.xxx.bm");
> bm.$init.implementation = function (ctx, conf) {
> this.$init(ctx, conf);
> 
> ```
> 	var mi_obj = mi.$new();
>     // This loader is DexClassLoader for dyn.dex
> 	var loader = mi.e.overload("com.xxx.xxx.md").call(mi_obj, conf);
> 	bmi.$dispose(mi_obj);
> 
>    // Use Java method get Class<?>
> 	var cls = loader.findClass("dyn.classA");
> 	
>   // is there any way to hook method of dyn.classA ?
>   // can't use Java.use("dyn.classA"),   error: class not found
>   // cls.a.implementation = ..., error: a is undefined
>  // How to convert cls to klass return by Java.use()? 
> }
> ```

try Java.factory.loader = loader;
And  how did you get  the loader of DexClassLoader for dyn.dex ?
