### ISSUE TITLE
vm and classFactory is not initialised when using gadget in script mode.

### ISSUE THREAD

**Issue by cosmosgenius** [frida/frida-java#68]
https://github.com/frida/frida-java/blob/d89c77c5da8c20a99f7ad36a33aa474c31eb00b2/index.js#L30-L36

The issue is `tryGetApi()` returns null when the `initialize` function is called the first time, as the env is loaded by then. By the time api is ready its already too late as `initialize` is never called again.

I have tested by moving 
```
    if (api !== null) {
      vm = new VM(api);
      classFactory = new ClassFactory(vm);
    }
```
below https://github.com/frida/frida-java/blob/d89c77c5da8c20a99f7ad36a33aa474c31eb00b2/index.js#L47 and it seems to work.

I can open a PR with the same if the solution seems fine!.

**Comment by cosmosgenius** [comment]
@oleavr any update on this?

**Comment by oleavr** [comment]
@cosmosgenius No sorry I've been busy elsewhere. Please open a PR and it will be easier to discuss what a good solution would be.

**Comment by cosmosgenius** [comment]
@oleavr i have opened a PR #71. Let me know. Thx
