### ISSUE TITLE
Anyway to add fields to registerClass(...)

### ISSUE THREAD

**Issue by wakawaka54** [frida/frida-java#76]
Is there anyway to add fields to a class created through the registerClass API?

i.e.

```java
Java.registerClass({
   name: 'com.test.RunnableComponent',
   implements: [Runnable]
   fields: {
      'myField': {
           accessor: 'private',
           type: 'java.lang.String' 
      }
   },
   methods: {
       'run': function() {
           console.log(this.myField);
       }
  }
});

var test = Java.use('com.test.RunnableComponent').$init();
test.myField = 'a string';
test.run();
```

Expected Log:
**a string**

**Comment by oleavr** [comment]
Not yet, but I would encourage you to add a test for it [here](https://github.com/frida/frida-java/blob/master/test/re/frida/ClassCreationTest.java) and take a stab at implementing it. What I usually do is:
1. Edit [this](https://github.com/frida/frida-java/blob/b840b14ba7ccd503eb7e794af675a1983e87abd4/test/re/frida/TestRunner.java#L23-L27) part of TestRunner.java to only run the test-suite I'm focusing on. In this case that means `"re.frida.ClassCreationTest"`.
2. Comment out the `@Test` annotations for the other tests in that suite.
3. Run `make check` once to compile the Java code and verify that the test I wrote does indeed fail as expected.
4. Run `make develop` so it monitors the JavaScript code for changes and auto-runs the test whenever there's a chance. This way I get really fast feedback as I work on the implementation.

And there's definitely a way more elegant way to do 1. and 2, in case you're interested in looking into that. :-)

Also, to improve performance and get an even faster feedback loop, edit [test/config.mk](https://github.com/frida/frida-java/blob/master/test/config.mk) and use an x86 emulator, e.g. Genymotion.

**Comment by gebing** [comment]
@oleavr 
I made an implement and pull request for this feature.
