### ISSUE TITLE
How to create a Integer.TYPE(int.class) array?

### ISSUE THREAD

**Issue by ghostmaze** [frida/frida-java#78]
Hi oleavr:
I have a question in "java.lang.Class.getMethod".

`public Method getMethod(String name, Class<?>... parameterTypes)
    throws NoSuchMethodException, SecurityException {
    return getMethod(name, parameterTypes, true);
}`

the second parameter need a "[Ljava.lang.Object;" type, and java code like this:

getMethod("say", new Class[]{String.class,int.class});
getMethod("say", new Class[]{Integer.TYPE,Integer.TYPE});

so How can i create this array using js or other ways ?

in addition,I created a obj array like this:
`var Integerclass = Java.use("java.lang.Integer");`
`var objectArr = Java.array('Ljava.lang.Class;',[Integerclass.TYPE,Integerclass.TYPE]);`

but i got a "invalid argument value" error.
`{'type': 'error', 'description': 'Error: invalid argument value', 'stack': 'Error: invalid argument value\n    at frida/node_modules/frida-java/lib/env.js:515\n    at frida/node_modules/frida-java/lib/class-factory.js:2592\n    at toJniObjectArray (frida/node_modules/frida-java/lib/class-factory.js:2640)\n    at java.js:4489\n    at frida/node_modules/frida-java/lib/class-factory.js:743\n    at [anon] (script1.js:28)\n    at input:1', 'fileName': 'frida/node_modules/frida-java/lib/env.js', 'lineNumber': 515, 'columnNumber': 1}`

**Comment by ghostmaze** [comment]
i got it

**Comment by Lesmm** [comment]
Hi, @ghostmaze , how do you resolve it ?  how to present **int.class** or **Integer.TYPE** in frida js ?  I encountered the same problem . Thx in advance.

**Comment by Lesmm** [comment]
I got it now too !

        // For JavaSE Impl 'getPrimitiveClass' method is in 'java.lang.Class'; For Android Impl below:
        var VMClassLoader = Java.use("java.lang.VMClassLoader"); 
        var intPrimitiveClass = VMClassLoader.getPrimitiveClass('I');

        var Integer = Java.use("java.lang.Integer");
        var intInstance = Integer.valueOf(0);

**Comment by zxhubo** [comment]
@ghostmaze I have the same problem,how do you resolve it ?

**Comment by zxhubo** [comment]
@Lesmm VMClassLoader variable do not have property，because I print the all of method of VMClassLoader variable：
```
private static libcore.io.ClassPathURLStreamHandler[] java.lang.VMClassLoader.createBootClassPathUrlHandlers()
static native java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader,java.lang.String)
private static native java.lang.String[] java.lang.VMClassLoader.getBootClassPathEntries()
static java.net.URL java.lang.VMClassLoader.getResource(java.lang.String)
static java.util.List java.lang.VMClassLoader.getResources(java.lang.String)
private static libcore.io.ClassPathURLStreamHandler[] java.lang.VMClassLoader.createBootClassPathUrlHandlers()
static native java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader,java.lang.String)
private static native java.lang.String[] java.lang.VMClassLoader.getBootClassPathEntries()
static java.net.URL java.lang.VMClassLoader.getResource(java.lang.String)
static java.util.List java.lang.VMClassLoader.getResources(java.lang.String)
```
why ？

**Comment by zxhubo** [comment]
@Lesmm how did you resolve this issue,how to create int.class or float.class and other basic type by frida's js ?

**Comment by zxhubo** [comment]
I got it,too.

**Comment by icew4y** [comment]
> I got it,too.

please,can you tell me how  resolve this issue?
