### ISSUE TITLE
Can't hook functions of classes inside interface

### ISSUE THREAD

**Issue by Chan9390** [frida/frida-java#88]
Hey,

I have been using Frida to hook the functions of classes and its been successful so far. But I came across a situation where a class is present inside an interface and its directly imported and used.

Example,

```java
public interface InterfaceA {

    public static class TargetClass extends xyz {
        public String TargetMethod() {
            // does something
            return z;
        }
    }
}
```

This interface is directly imported and used in other packages. Example: `import com.package.name.InterfaceA.TargetClass` and the method is directly used `(new TargetClass).TargetMethod()`.

I tried to hook with the following code, but didnt work.

```javascript
        var AttestationResponse = Java.use("com.package.name.InterfaceA.TargetClass");
        TargetClass.TargetMethod.implementation = function () {
            console.log("[+] TargetMethod called");
            return this.TargetMethod();
        }
```

Any solutions on how to hook the function ?

**Comment by Chan9390** [comment]
I found out that the interface was extended in a class at a different location.

**Comment by josebeo2016** [comment]
> I found out that the interface was extended in a class at a different location.

can you show me how to hook AttestationResponse class?
