### ISSUE TITLE
Java.perform doesn't work even with Java Available

### ISSUE THREAD

**Issue by mvastola** [frida/frida-java#89]
I'm having an issue where I can't get *anything* inside a `Java.perform` to work, even if `Java.available` returns true. Since none of the `Java` methods seem to work unless they're called from a `Java.perform`, this makes the Java interface unusable.

A simple example case is the following JS:
```js
'use strict';

const frida = require('frida');

const processName = process.argv[3];
let api;

const source = `'use strict';
rpc.exports = {};
rpc.exports.javaTest = function() {
  console.log('Inside RPC call.');
  if(!Java.available) {
    console.log("Java not loaded yet.");
    return false;
  }
  console.log("Java is available.");
  Java.perform(function() {
    console.log("Inside Java.perform.");
    throw 'This script should crash right here';
  });
  console.log('After Java.perform.');
  return true;
}`;

async function dumpJavaClasses() {
  console.log('Starting RPC Call');
  let result = await api.javaTest();
  console.log('RPC call returned ', result);
};

async function main() {
  const dev = await frida.getDeviceManager().addRemoteDevice(process.argv[2]);
  const pid = await dev.spawn(processName);
  const session = await dev.attach(pid);
  const script = await session.createScript(source);
  await script.load();
  api = script.exports;
  setTimeout(dumpJavaClasses, 5000);
}

main()
  .catch(e => {
    console.error(e);
  });
```

My output is:
```
Starting RPC Call
Inside RPC call.
Java is available.
After Java.perform.
RPC call returned  true
```

The expected output should include an `Inside Java.perform.` line logged to the console, followed by the script aborting.

I considered that something weird was happening where the Java VM isn't active inside the current thread (I have no idea if that's even possible) but I can't call `Java.scheduleOnMainThread` outside `Java.perform` so it's kind of a catch-22. (There's also no way to evaluate code on a specific thread, AFAIK.)

Finally no errors are being thrown whatsoever. (The process exits cleanly with a status code of `0`.)

**Comment by TheDauntless** [comment]
I haven't used this RPC approach myself, but aren't you forgetting to resume the app/thread? (`dev.resume(pid)`)

**Comment by mvastola** [comment]
Okay. So that was exceedingly simple. I'm confused though. I thought that pausing until the script is resumed after spawn was only needed if spawngating was enabled. Or am I totally off the mark?

**Comment by oleavr** [comment]
Calling `Java.perform()`, as opposed to `Java.performNow()`, will ensure that the app's classes are available before calling your callback. That means you have to call `resume()` *after* you have scheduled a `Java.perform()`, so the process continues booting up and reaches the point where the app's classes are available.

**Comment by oleavr** [comment]
(Be careful so you schedule this *before* `resume()`, though, as you otherwise might miss some early calls.)
