### ISSUE TITLE
building frida-server for ARMv7 #2

### ISSUE THREAD

**Issue by iddoeldor** [frida/frida-java#96]
[related issue](https://github.com/frida/frida-java/issues/95)

```
$ make build/frida-android-arm/lib/pkgconfig/frida-core-1.0.pc
make[1]: Entering directory '/home/frida'
make[1]: 'build/frida-android-arm/lib/pkgconfig/frida-core-1.0.pc' is up to date.
make[1]: Leaving directory '/home/frida'
```

What do I need change to build frida-server with my changes in frida-java ?

Patched locally `frida/frida-gum/bindings/gumjs/node_modules/frida-java/lib/class-factory.js`

**Comment by oleavr** [comment]
```
cd frida/frida-gum
npm link /path/to/your/frida-java
```

Then `make clean` and build Frida again.

**Comment by oleavr** [comment]
But if you're hacking on frida-java it's much easier to use frida-compile to link your custom frida-java into an agent instead. Here's a recipe:
https://gist.github.com/oleavr/cae76c895eb7d227216ed3ffe9dbbeb3

And if you want to use TypeScript (recommended) then there's some boilerplate here:
https://github.com/oleavr/frida-agent-example
