### ISSUE TITLE
Invalid abi specified error caused by change in NativeFunction implementation

### ISSUE THREAD

**Issue by eanker** [frida/frida-java#98]
When running the [frida-java playground example](https://gist.github.com/oleavr/cae76c895eb7d227216ed3ffe9dbbeb3) with the current version of frida-java the error below occurs:

```
Error: invalid abi specified
    at ../frida-java/lib/android.js:236:42
    at Array.forEach (<anonymous>)
    at ../frida-java/lib/android.js:228:5
    at Array.forEach (<anonymous>)
    at _getApi (../frida-java/lib/android.js:214:3)
    at getApi (../frida-java/lib/android.js:40:17)
    at tryInitialize (../frida-java/index.js:40:13)
    at new Runtime (../frida-java/index.js:440:3)
    at Object.28../lib/android (../frida-java/index.js:443:18)
    at o (node_modules/browser-pack/_prelude.js:1:1)
```

I tried multiple tags of frida-java and found that only 2.0.4 and 2.0.3 give me this error. 
Testing the commits between 2.0.2 and 2.03, I could pin pointed commit [`5c3da5560e414c73356266543d973b33b02157a5`](https://github.com/frida/frida-java/commit/5c3da5560e414c73356266543d973b33b02157a5) as the cause. This seems logical as the first error reported is in a new native function call.

I do not know what code change triggered this issue, as I do have insufficient knowledge of the frida-java framework.

Environment
phone:
```
abi: [armeabi-v7a,armeabi]
api: 23
```

pc:
```
sdk: 28.0.3
ndk: r15c
platform: Ubuntu 18.04
```

**Comment by oleavr** [comment]
This means that the device-side Frida is too old. Newer versions of frida-java require newer Frida (GumJS). Cheers!
